CREATE TABLE IF NOT EXISTS products ( 
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  price INTEGER NOT NULL,
  quantity INTEGER NOT NULL,
  category_id INTEGER NOT NULL REFERENCES categories(id)
);
