CREATE TABLE IF NOT EXISTS customers (
  id SERIAL PRIMARY KEY,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  city TEXT NOT NULL UNIQUE,
  state TEXT NOT NULL UNIQUE,
  zip_code TEXT NOT NULL UNIQUE
);
